### ISSUE TITLE
Add a readme?

### ISSUE THREAD

**Issue by QwertyJack** [mytbk/DPPL#1]
Vimacs大婶你好！

我来自bdwm，这学期选了DPPL，一下被你的repo名字吸引进来，又是熟悉的OCaml，又是熟悉的 core, syntax, lexer, parser... 。 

这是你的 final project 么？能不能来个 test.f 或者 readme 以供我拜读与学习？

先谢为敬～

**Comment by mytbk** [comment]
的确是final project. 
我刚刚看了我队友的repo: https://github.com/shiyqw/DPPL 里面有一个report,里面的示例代码应该能用。

**Comment by QwertyJack** [comment]
原来你就是大名鼎鼎的菜菜啊 !!!
啊啊啊(膜拜)

你们做这个理论很深奥啊～一时半会儿还不太能理解。
